
export const FETCH_TODOS_REQUEST = 'FETCH_TODOS_REQUEST';
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS';
export const FETCH_TODOS_ERROR = 'FETCH_TODOS_ERROR';

export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_ERROR = 'ADD_TODO_ERROR';

export const REMOVE_TODO_REQUEST = 'REMOVE_TODO_REQUEST';
export const REMOVE_TODO_SUCCESS = 'REMOVE_TODO_SUCCESS';
export const REMOVE_TODO_ERROR = 'REMOVE_TODO_ERROR';

export const CHECK_TODO_REQUEST = 'CHECK_TODO_REQUEST';

export const DELETE_TODOS_REQUEST = 'DELETE_TODOS_REQUEST';
export const DELETE_TODOS_SUCCESS = 'DELETE_TODOS_SUCCESS';
export const DELETE_TODOS_ERROR = 'DELETE_TODOS_ERROR';
